return {
  max_concurrent_installers = 6,
  ui = {
    icons = {
      package_installed = "✓",
      package_pending = "➜",
      package_uninstalled = "✗",
    },
  },
  ensure_installed = {
    "ansible-language-server",
    "ansible-lint",
    "ast-grep",
    "bash-language-server",
    "codelldb",
    "delve",
    "gh",
    "gitleaks",
    "gofumpt",
    "goimports",
    "golangci-lint",
    "gomodifytags",
    "gopls",
    "gotests",
    "gotestsum",
    "impl",
    "lua-language-server",
    "markdown-toc",
    "markdownlint-cli2",
    "marksman",
    "ruff",
    "basedpyright",
    "debugpy",
    "iferr",
    "semgrep",
    "shellcheck",
    "shfmt",
    "stylua",
    "taplo",
    "tfsec",
    "tree-sitter-cli",
    "uv",
    "yaml-language-server",
  },
}
